INSERT INTO ALIEN VALUES(1,'KUNAL','JAVA');
INSERT INTO ALIEN VALUES(2,'JATTA','JAVA');
INSERT INTO ALIEN VALUES(3,'GATTA','PTHON');
INSERT INTO ALIEN VALUES(4,'ALOO','JAVA');
INSERT INTO ALIEN VALUES(5,'TOKA','ANDROID');
